<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Catalog\Catalog.Contracts\Catalog.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Insights\Insights.Contracts\Insights.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Lending\Lending.Contracts\Lending.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.StatusProto" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
