<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IncludeGoogleApiCommonProtos>true</IncludeGoogleApiCommonProtos>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="lending.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
