<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Catalog\Catalog\Catalog.csproj" />
    <ProjectReference Include="..\Modules\Lending\Lending\Lending.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="All" />
  </ItemGroup>

</Project>
