<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Library.Shared\Library.Shared.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog\Catalog.csproj" />
    <ProjectReference Include="..\Modules\Insights\Insights\Insights.csproj" />
    <ProjectReference Include="..\Modules\Lending\Lending\Lending.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.HealthChecks" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
    <PackageReference Include="Mediator.SourceGenerator" PrivateAssets="All" />
  </ItemGroup>

</Project>
