<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Library.Shared\Library.Shared.csproj" />
    <ProjectReference Include="..\..\src\Library.Warmup\Library.Warmup.csproj" />
    <ProjectReference Include="..\..\src\Modules\Lending\Lending\Lending.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

</Project>
