<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Library.Api\Library.Api.csproj" />
    <ProjectReference Include="..\..\src\Library.Migrations\Library.Migrations.csproj" />
    <ProjectReference Include="..\..\src\Library.Service\Library.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

</Project>
